name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-checks:
    runs-on: ubuntu-latest
    container:
      image: agrobotappliedai/webdev-containers:latest
      options: --user root

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Add bun to PATH
        id: path
        run: echo "/home/vscode/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        id: install
        run: bun install --frozen-lockfile

      - name: Check format
        id: fmt
        run: bun run fmt:check

      - name: Check lint
        id: lint
        run: bun run lint:check

      - name: Check build
        id: check
        run: bun run build:check

